version: "3.8"

networks:
  prod-web-vpc:
    name: prod-web-vpc
    external: true

services:
  blog:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: blog
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - prod-web-vpc
