version: '3'

services:
  blog:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: blog
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - alya-prod-public

networks:
  alya-prod-public:
    external: true
